from textwrap import dedent

from crewai import Task

from src.infra.ai.agents.publisher import publisher
from src.infra.ai.tasks.content_creation import content_creation_task
from src.infra.ai.tasks.prompt_creation import prompt_creation_task

final_response_task = Task(
    description=dedent(
        """
        Combine the content generated by the Editor agent and the Designer
        agent and create a final response. Do not change anything in the content,
        just combine the two contents and a single response separated by agents.
        """
    ),
    expected_output='Combined final answer.',
    tools=[],
    agent=publisher,
)

final_response_task.context = [content_creation_task, prompt_creation_task]
